version: "3"
services:
  redis:
    image: blog
    ports:
      - "6379"
    networks:
      - host
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

 
networks:
  frontend:
  backend:
 
volumes:
  db-data: